import React, { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import {
  PiHeart, PiStar, PiFlower, PiSun, PiLeaf, PiCheck, PiPlus, PiGift,
  PiCake, PiCamera, PiCoffee, PiPizza, PiTree, PiFish, PiBird, PiCat,
  PiMusicNote, PiBookmark, PiMapPin, PiEnvelope, PiPhone, PiSparkle,
  PiMoon, PiCloud, PiCloudSun, PiCloudRain, PiSnowflake, PiRainbow, PiLightning, PiFire,
  PiHouse, PiCar, PiAirplane, PiBicycle, PiRocket, PiAnchor, PiBalloon, PiSailboat,
  PiFlag, PiTrophy, PiMedal, PiCrown, PiDiamond, PiDiamondsFour,
  PiDog, PiPawPrint, PiButterfly, PiTreePalm, PiTreeEvergreen, PiFlowerLotus, PiFlowerTulip,
  PiHamburger, PiCookie, PiIceCream, PiWine, PiBeerBottle,
  PiSmiley, PiSmileyWink, PiHeartStraight, PiStarHalf, PiThumbsUp, PiThumbsDown,
  PiCircle, PiSquare, PiHexagon, PiTriangle,
  PiUser, PiUsers, PiEnvelopeOpen, PiVideoCamera, PiWatch,
  PiSunglasses, PiUmbrella, PiMountains, PiWaves,
} from 'react-icons/pi';

export const CANVAS_SIZE = 680;

export const FABRIC_JSON_PROPS = [
  'name',
  'excludeFromExport',
  'curveType',
  'dataId',
  'dataRole',
  'locked',
  'lockMovementX',
  'lockMovementY',
  'lockScalingX',
  'lockScalingY',
  'lockRotation',
  'hasControls',
];

export const CURVE_PRESETS = {
  arcUp: 'M 0 80 Q 100 0 200 80',
  arcDown: 'M 0 0 Q 100 80 200 0',
  wave: 'M 0 40 Q 50 0 100 40 Q 150 80 200 40',
  arcLeft: 'M 80 0 Q 0 50 80 100',
  arcRight: 'M 0 0 Q 80 50 0 100',
};

export const ICON_LIST = [
  { Icon: PiHeart, label: 'Trai tim' },
  { Icon: PiHeartStraight, label: 'Trai tim thang' },
  { Icon: PiStar, label: 'Ngoi sao' },
  { Icon: PiStarHalf, label: 'Nua sao' },
  { Icon: PiSparkle, label: 'Lap lanh' },
  { Icon: PiFlower, label: 'Hoa' },
  { Icon: PiFlowerLotus, label: 'Hoa sen' },
  { Icon: PiFlowerTulip, label: 'Tulip' },
  { Icon: PiSun, label: 'Mat troi' },
  { Icon: PiMoon, label: 'Mat trang' },
  { Icon: PiCloud, label: 'May' },
  { Icon: PiCloudSun, label: 'May nang' },
  { Icon: PiCloudRain, label: 'May mua' },
  { Icon: PiSnowflake, label: 'Tuyet' },
  { Icon: PiRainbow, label: 'Cau vong' },
  { Icon: PiLightning, label: 'Set' },
  { Icon: PiFire, label: 'Lua' },
  { Icon: PiLeaf, label: 'La' },
  { Icon: PiTree, label: 'Cay' },
  { Icon: PiTreePalm, label: 'Cay co' },
  { Icon: PiTreeEvergreen, label: 'Cay thong' },
  { Icon: PiMountains, label: 'Nui' },
  { Icon: PiWaves, label: 'Song' },
  { Icon: PiCheck, label: 'Dau kiem' },
  { Icon: PiPlus, label: 'Dau cong' },
  { Icon: PiGift, label: 'Qua' },
  { Icon: PiCake, label: 'Banh' },
  { Icon: PiCoffee, label: 'Ca phe' },
  { Icon: PiPizza, label: 'Pizza' },
  { Icon: PiHamburger, label: 'Hamburger' },
  { Icon: PiCookie, label: 'Banh quy' },
  { Icon: PiIceCream, label: 'Kem' },
  { Icon: PiWine, label: 'Ruou' },
  { Icon: PiBeerBottle, label: 'Bia' },
  { Icon: PiCamera, label: 'May anh' },
  { Icon: PiFish, label: 'Ca' },
  { Icon: PiBird, label: 'Chim' },
  { Icon: PiCat, label: 'Meo' },
  { Icon: PiDog, label: 'Cho' },
  { Icon: PiPawPrint, label: 'Dau chan' },
  { Icon: PiButterfly, label: 'Buom' },
  { Icon: PiMusicNote, label: 'Not nhac' },
  { Icon: PiBookmark, label: 'Danh dau' },
  { Icon: PiMapPin, label: 'Vi tri' },
  { Icon: PiEnvelope, label: 'Thu' },
  { Icon: PiEnvelopeOpen, label: 'Thu mo' },
  { Icon: PiPhone, label: 'Dien thoai' },
  { Icon: PiHouse, label: 'Nha' },
  { Icon: PiCar, label: 'Xe hoi' },
  { Icon: PiAirplane, label: 'May bay' },
  { Icon: PiBicycle, label: 'Xe dap' },
  { Icon: PiRocket, label: 'Ten lua' },
  { Icon: PiAnchor, label: 'Mo neo' },
  { Icon: PiBalloon, label: 'Bong bay' },
  { Icon: PiSailboat, label: 'Thuyen buom' },
  { Icon: PiFlag, label: 'Co' },
  { Icon: PiTrophy, label: 'Cup' },
  { Icon: PiMedal, label: 'Huy chuong' },
  { Icon: PiCrown, label: 'Vuong mien' },
  { Icon: PiDiamond, label: 'Kim cuong' },
  { Icon: PiDiamondsFour, label: 'Bon o' },
  { Icon: PiSmiley, label: 'Mat cuoi' },
  { Icon: PiSmileyWink, label: 'Mat nhay mat' },
  { Icon: PiThumbsUp, label: 'Thich' },
  { Icon: PiThumbsDown, label: 'Khong thich' },
  { Icon: PiCircle, label: 'Hinh tron' },
  { Icon: PiSquare, label: 'Hinh vuong' },
  { Icon: PiHexagon, label: 'Luc giac' },
  { Icon: PiTriangle, label: 'Tam giac' },
  { Icon: PiUser, label: 'Nguoi' },
  { Icon: PiUsers, label: 'Nhom nguoi' },
  { Icon: PiVideoCamera, label: 'May quay' },
  { Icon: PiWatch, label: 'Dong ho' },
  { Icon: PiSunglasses, label: 'Kinh ram' },
  { Icon: PiUmbrella, label: 'O' },
];

export const FONT_OPTIONS = [
  { value: 'Arial', label: 'Arial' },
  { value: 'Helvetica', label: 'Helvetica' },
  { value: 'Georgia', label: 'Georgia' },
  { value: 'Times New Roman', label: 'Times New Roman' },
  { value: 'Verdana', label: 'Verdana' },
  { value: 'Courier New', label: 'Courier New' },
  { value: 'Impact', label: 'Impact' },
  { value: 'Inter', label: 'Inter' },
  { value: 'Roboto', label: 'Roboto' },
  { value: 'Open Sans', label: 'Open Sans' },
  { value: 'Lato', label: 'Lato' },
  { value: 'Poppins', label: 'Poppins' },
  { value: 'Montserrat', label: 'Montserrat' },
  { value: 'Raleway', label: 'Raleway' },
  { value: 'Oswald', label: 'Oswald' },
  { value: 'Rubik', label: 'Rubik' },
  { value: 'Nunito', label: 'Nunito' },
  { value: 'Work Sans', label: 'Work Sans' },
  { value: 'Source Sans Pro', label: 'Source Sans Pro' },
  { value: 'Fira Sans', label: 'Fira Sans' },
  { value: 'Ubuntu', label: 'Ubuntu' },
  { value: 'PT Sans', label: 'PT Sans' },
  { value: 'Noto Sans', label: 'Noto Sans' },
  { value: 'DM Sans', label: 'DM Sans' },
  { value: 'Outfit', label: 'Outfit' },
  { value: 'Manrope', label: 'Manrope' },
  { value: 'Plus Jakarta Sans', label: 'Plus Jakarta Sans' },
  { value: 'Lexend', label: 'Lexend' },
  { value: 'Figtree', label: 'Figtree' },
  { value: 'Karla', label: 'Karla' },
  { value: 'Mukta', label: 'Mukta' },
  { value: 'Cabin', label: 'Cabin' },
  { value: 'Josefin Sans', label: 'Josefin Sans' },
  { value: 'Archivo', label: 'Archivo' },
  { value: 'Barlow', label: 'Barlow' },
  { value: 'Kanit', label: 'Kanit' },
  { value: 'Playfair Display', label: 'Playfair Display' },
  { value: 'Merriweather', label: 'Merriweather' },
  { value: 'Roboto Slab', label: 'Roboto Slab' },
  { value: 'Cormorant Garamond', label: 'Cormorant Garamond' },
  { value: 'Anton', label: 'Anton' },
  { value: 'Righteous', label: 'Righteous' },
  { value: 'Bebas Neue', label: 'Bebas Neue' },
  { value: 'Dancing Script', label: 'Dancing Script' },
  { value: 'Pacifico', label: 'Pacifico' },
  { value: 'Lobster', label: 'Lobster' },
  { value: 'Great Vibes', label: 'Great Vibes' },
  { value: 'Satisfy', label: 'Satisfy' },
  { value: 'Quicksand', label: 'Quicksand' },
  { value: 'Comfortaa', label: 'Comfortaa' },
  { value: 'Kalam', label: 'Kalam' },
  { value: 'Philosopher', label: 'Philosopher' },
  { value: 'Syne', label: 'Syne' },
  { value: 'Tilt Neon', label: 'Tilt Neon' },
  { value: 'Signika', label: 'Signika' },
  { value: 'Exo 2', label: 'Exo 2' },
  { value: 'Maven Pro', label: 'Maven Pro' },
  { value: 'Inconsolata', label: 'Inconsolata' },
  { value: 'JetBrains Mono', label: 'JetBrains Mono' },
  { value: 'Space Mono', label: 'Space Mono' },
];

export const FONT_SIZE_PRESETS = [12, 14, 16, 20, 24, 32, 40, 48, 64, 96];

export const TEXT_PRESETS = [
  {
    id: 'headline',
    eyebrow: 'Hero',
    title: 'TIEU DIEM',
    caption: 'Headline lon cho mat truoc',
    text: 'TIEU DIEM',
    tone: 'bold',
    style: { fontFamily: 'Anton', fontSize: 44, fontWeight: '700', fill: '#ffffff', textAlign: 'center' },
  },
  {
    id: 'signature',
    eyebrow: 'Signature',
    title: 'Green Notes',
    caption: 'Kieu chu mem va ca nhan',
    text: 'Green Notes',
    tone: 'script',
    style: { fontFamily: 'Pacifico', fontSize: 34, fontWeight: '400', fill: '#22c55e', textAlign: 'center' },
  },
  {
    id: 'badge',
    eyebrow: 'Badge',
    title: 'Eco Club',
    caption: 'Cum chu ngan de ghep icon',
    text: 'Eco Club',
    tone: 'clean',
    style: { fontFamily: 'Plus Jakarta Sans', fontSize: 28, fontWeight: '700', fill: '#e5eef7', textAlign: 'center', charSpacing: 40 },
  },
];

export const isEditableCanvasObject = (object) => {
  if (!object) return false;
  if (object.dataRole === 'system') return false;
  if (object.name === '__bgRect__') return false;
  if (object.excludeFromExport) return false;
  return true;
};

export const iconToSvgString = (IconComponent, fill = '#111827') => {
  return renderToStaticMarkup(
    createElement(IconComponent, {
      size: 64,
      color: fill,
      strokeWidth: 1.8,
    }),
  );
};
